### ISSUE TITLE
Couldn't load builder file: /usr/local/share/brp-pacu/BRP_PACU.ui

### ISSUE THREAD

**Issue by matthew-dews** [matthew-dews/brp-pacu#15]
This error appears after trying to run the BRP_PACU executable after the initial build (sans "sudo make install"). Running "sudo make install" fixes this, but means that after any UI changes, "sudo make install" must be run.

**Comment by nettings** [comment]
see #20 for a quick fix (sorry, I'm new to pull requests, somehow this slipped into an unrelated one).

**Comment by matthew-dews** [comment]
Thanks for also knocking this out in addition to #19.

Here's a good article on closing issues via pull requests: https://help.github.com/articles/closing-issues-via-commit-messages/
