### ISSUE TITLE
Check pink noise generator for correctness.

### ISSUE THREAD

**Issue by matthew-dews** [matthew-dews/brp-pacu#19]
A while ago I tried to test BRP-PACU on a live system and myself and a colleague observed that the pink noise generator seemed to be lacking in the high end when compared to the pink noise generated by a Yamaha LS-9. The audio interface was a Digidesign MBox2.

**Comment by nettings** [comment]
I think that's unlikely. My measurements show the opposite: the BRP_PACU pink noise rolls off in the bass.
![brp_pacu noise generator](https://cloud.githubusercontent.com/assets/6558129/25809540/94d0a584-340d-11e7-8d4d-e1cbef727f31.png)

**Comment by nettings** [comment]
#20

**Comment by matthew-dews** [comment]
Closed by #20

**Comment by matthew-dews** [comment]
EDIT: User error, it is operating as intended, I made a mistake with how and what I hooked up.
